server:
  port: 8082
  # 测试线程隔离
#  tomcat:
#    threads:
#      max: 25
#    accept-count: 25
#    max-connections: 100
feign:
  okhttp:
    enabled: true # 开启OKHttp
  client:
    default-config: okhttp
  sentinel:
    enabled: true # 添加到sentinel簇点资源
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # sentinel的控制台地址
      http-method-specify: true # 开启请求方式前缀
